export const actionTypes = {
    GET_USER : "GET_USER",
    USER_FOUND : "USER_FOUND",
    USER_NOT_FOUND : "USER_NOT_FOUND",
    
    GET_REPOS : "GET_REPOS",
    REPOS_FOUND : "REPOS_FOUND",
    REPOS_NOT_FOUND : "REPOS_NOT_FOUND"
}