const GET_USER = "GET_USER";
const USER_FOUND = "USER_FOUND";
const USER_NOT_FOUND = "USER_NOT_FOUND";

const GET_REPOS = "GET_REPOS";
const REPOS_FOUND = "REPOS_FOUND";
const REPOS_NOT_FOUND = "REPOS_NOT_FOUND";

export {
    GET_USER,
    USER_FOUND,
    USER_NOT_FOUND,
    GET_REPOS,
    REPOS_FOUND,
    REPOS_NOT_FOUND
}